### ISSUE TITLE
训练显存问题

### ISSUE THREAD

**Issue by czw111** [mankasto/iLRG#1]
您好，想问下您进行ResNet-50 on ImageNet的实验用的设备是什么呢，当batchSize为4096时显存占用为多少呢？
我这边batchSize在512的时候显存占用达到了40G（单卡A800-80G），在batchSize为1024的时候80G的显存就不太够了
所以想问下您是怎么解决这个显存不够的问题的

**Comment by mankasto** [comment]
您好，我这边是通过把大batch等分成小batch后分别输入模型计算梯度然后再聚合的，可以通过参数max_size来设置，设置为1的话在24G显存的3090上batch size 4096是可以跑通的

**Comment by czw111** [comment]
好的，感谢
